export const RANDOM_DEGEN_SPEC = Object.freeze({
  id: "random_degen_v2",
  version: "2.0.0",
  mode: "layered_pixel_generator",
  canvas: {
    width: 32,
    height: 32,
    backgroundIndex: 0,
    view: "strict_side_profile_right",
  },
  palette: {
    size: 16,
    slots: {
      "0": { name: "bg_or_custom", hex: "#650c7e", role: "background_or_custom" },
      "1": { name: "white", hex: "#f2f2f2", role: "highlight" },
      "2": { name: "red", hex: "#d14f4f", role: "hair_red" },
      "3": { name: "green", hex: "#52c86b", role: "zombie_or_alien" },
      "4": { name: "blue", hex: "#5874d8", role: "hoodie_blue" },
      "5": { name: "gold", hex: "#d9ac3f", role: "crown_gold" },
      "6": { name: "orange", hex: "#c3763b", role: "cigarette_tip_or_pipe" },
      "7": { name: "violet", hex: "#7f5ad8", role: "rare_alt" },
      "8": { name: "cyan", hex: "#53bdd0", role: "visor_cyan" },
      "9": { name: "pink", hex: "#cf62ae", role: "3d_glasses_pink" },
      "10": { name: "olive", hex: "#607b42", role: "zombie_shadow" },
      "11": { name: "brown", hex: "#7b4b31", role: "skin_shadow_or_ape" },
      "12": { name: "bone", hex: "#d7ccb0", role: "light_skin_or_bone" },
      "13": { name: "slate", hex: "#555b72", role: "glasses_dark_or_smoke" },
      "14": { name: "peach", hex: "#dfb187", role: "tan_skin" },
      "15": { name: "light_blue", hex: "#9bbde3", role: "pale_blue_or_alt_skin" },
    },
    roleBindings: {
      skin_light: 12,
      skin_tan: 14,
      skin_dark: 11,
      skin_pale: 15,
      skin_zombie: 10,
      skin_alien_green: 3,
      skin_alien_blue: 15,
      skin_ape: 11,
      shadow_human: 11,
      shadow_zombie: 10,
      shadow_alien: 10,
      shadow_ape: 13,
      hair_red: 2,
      hair_black: 13,
      hair_white: 1,
      hair_brown: 11,
      hoodie_blue: 4,
      hoodie_dark: 13,
      shirt_dark: 13,
      visor: 8,
      glasses_black: 13,
      glasses_dark: 13,
      laser: 2,
      crown: 5,
      white: 1,
      cigarette_white: 1,
      cigarette_tip: 6,
      smoke: 13,
      earring: 5,
      teeth: 1,
      bone: 12,
      "3d_left": 9,
      "3d_right": 4,
    },
  },
  anchors: {
    eye: { x: 16, y: 10 },
    mouth: { x: 16, y: 14 },
    hair: { x: 14, y: 5 },
    smoke: { x: 23, y: 10 },
    clothing: { x: 13, y: 21 },
    ear: { x: 10, y: 12 },
  },
  generationOrder: [
    "baseType",
    "skin",
    "beardShadow",
    "eyes",
    "mouth",
    "hair",
    "clothing",
    "accessory",
  ],
  base: {
    id: "punk_master_human_profile_v1",
    immutableLayers: ["base_head_neck", "ear", "nose_bridge_and_tip"],
    layers: {
      base_head_neck: [
        [12, 7],[13, 7],[14, 7],[15, 7],[16, 7],[17, 7],[18, 7],[19, 7],
        [11, 8],[12, 8],[13, 8],[14, 8],[15, 8],[16, 8],[17, 8],[18, 8],[19, 8],[20, 8],
        [11, 9],[12, 9],[13, 9],[14, 9],[15, 9],[16, 9],[17, 9],[18, 9],[19, 9],[20, 9],
        [11, 10],[12, 10],[13, 10],[20, 10],
        [10, 11],[11, 11],[12, 11],[13, 11],[14, 11],[15, 11],[16, 11],[17, 11],[18, 11],[19, 11],[20, 11],[21, 11],
        [10, 12],[11, 12],[12, 12],[13, 12],[14, 12],[15, 12],[16, 12],[17, 12],[18, 12],[19, 12],[20, 12],[21, 12],
        [10, 13],[11, 13],[12, 13],[13, 13],[14, 13],[15, 13],[16, 13],[17, 13],[18, 13],[19, 13],[20, 13],[21, 13],
        [11, 14],[12, 14],[13, 14],[14, 14],[15, 14],
        [11, 15],[12, 15],[13, 15],[14, 15],[15, 15],
        [11, 16],[12, 16],[13, 16],[14, 16],[15, 16],
        [11, 17],[12, 17],[13, 17],[14, 17],[15, 17],
        [12, 18],[13, 18],[14, 18],[15, 18],
        [12, 19],[13, 19],[14, 19],[15, 19],
        [12, 20],[13, 20],[14, 20],[15, 20],
        [12, 21],[13, 21],[14, 21],[15, 21],
      ],
      ear: [
        [10, 12],[10, 13],[10, 14],
        [11, 12],[11, 13],[11, 14],
      ],
      nose_bridge_and_tip: [
        [21, 11],
        [21, 12],[22, 12],
        [21, 13],[22, 13],
        [20, 14],
      ],
    },
  },
  traits: {
    baseType: {
      type: "metadata_gate",
      options: [
        { id: "human_male", weight: 58, tier: "common" },
        { id: "human_female", weight: 18, tier: "uncommon" },
        { id: "zombie", weight: 10, tier: "rare" },
        { id: "alien", weight: 7, tier: "epic" },
        { id: "ape", weight: 7, tier: "epic" },
      ],
    },
    skin: {
      type: "recolor",
      targetLayers: ["base_head_neck", "ear", "nose_bridge_and_tip"],
      options: [
        { id: "light", fillRole: "skin_light", weight: 28, tier: "common", allowedBaseTypes: ["human_male", "human_female"] },
        { id: "tan", fillRole: "skin_tan", weight: 28, tier: "common", allowedBaseTypes: ["human_male", "human_female"] },
        { id: "dark", fillRole: "skin_dark", weight: 20, tier: "common", allowedBaseTypes: ["human_male", "human_female"] },
        { id: "pale", fillRole: "skin_pale", weight: 10, tier: "uncommon", allowedBaseTypes: ["human_male", "human_female"] },
        { id: "zombie", fillRole: "skin_zombie", weight: 7, tier: "rare", allowedBaseTypes: ["zombie"] },
        { id: "alien_green", fillRole: "skin_alien_green", weight: 4, tier: "epic", allowedBaseTypes: ["alien"] },
        { id: "alien_blue", fillRole: "skin_alien_blue", weight: 2, tier: "epic", allowedBaseTypes: ["alien"] },
        { id: "ape", fillRole: "skin_ape", weight: 1, tier: "epic", allowedBaseTypes: ["ape"] },
      ],
    },
    beardShadow: {
      type: "overlay",
      options: [
        {
          id: "on",
          weight: 62,
          tier: "common",
          pixels: [
            { x: 16, y: 12 },{ x: 17, y: 12 },{ x: 18, y: 12 },{ x: 19, y: 12 },
            { x: 15, y: 13 },{ x: 16, y: 13 },{ x: 17, y: 13 },{ x: 18, y: 13 },{ x: 19, y: 13 },{ x: 20, y: 13 },
            { x: 15, y: 14 },{ x: 16, y: 14 },{ x: 17, y: 14 },{ x: 18, y: 14 },{ x: 19, y: 14 },{ x: 20, y: 14 },
            { x: 15, y: 15 },{ x: 16, y: 15 },{ x: 17, y: 15 },{ x: 18, y: 15 },{ x: 19, y: 15 },
            { x: 15, y: 16 },{ x: 16, y: 16 },{ x: 17, y: 16 },{ x: 18, y: 16 },{ x: 19, y: 16 },
          ],
          colorRoleByBaseType: {
            human_male: "shadow_human",
            human_female: "shadow_human",
            zombie: "shadow_zombie",
            alien: "shadow_alien",
            ape: "shadow_ape",
          },
        },
        { id: "off", weight: 38, tier: "common", pixels: [] },
      ],
    },
    eyes: {
      type: "overlay",
      options: [
        {
          id: "shades",
          weight: 26,
          tier: "uncommon",
          pixels: [
            { x: 14, y: 10, role: "glasses_black" },{ x: 15, y: 10, role: "glasses_black" },{ x: 16, y: 10, role: "glasses_black" },
            { x: 17, y: 10, role: "glasses_black" },{ x: 18, y: 10, role: "glasses_black" },{ x: 19, y: 10, role: "glasses_black" },
            { x: 14, y: 11, role: "glasses_black" },{ x: 15, y: 11, role: "glasses_black" },{ x: 16, y: 11, role: "glasses_black" },
            { x: 17, y: 11, role: "glasses_black" },{ x: 18, y: 11, role: "glasses_black" },{ x: 19, y: 11, role: "glasses_black" },
          ],
        },
        {
          id: "normal",
          weight: 22,
          tier: "common",
          pixels: [
            { x: 16, y: 10, role: "white" },
            { x: 17, y: 10, role: "white" },
          ],
        },
        {
          id: "tired",
          weight: 20,
          tier: "common",
          pixels: [
            { x: 15, y: 10, role: "glasses_dark" },
            { x: 16, y: 10, role: "glasses_dark" },
            { x: 17, y: 10, role: "glasses_dark" },
          ],
        },
        {
          id: "visor",
          weight: 10,
          tier: "rare",
          pixels: [
            { x: 14, y: 10, role: "visor" },{ x: 15, y: 10, role: "visor" },{ x: 16, y: 10, role: "visor" },
            { x: 17, y: 10, role: "visor" },{ x: 18, y: 10, role: "visor" },{ x: 19, y: 10, role: "visor" },
            { x: 14, y: 11, role: "glasses_dark" },{ x: 15, y: 11, role: "glasses_dark" },{ x: 16, y: 11, role: "glasses_dark" },
            { x: 17, y: 11, role: "glasses_dark" },{ x: 18, y: 11, role: "glasses_dark" },{ x: 19, y: 11, role: "glasses_dark" },
          ],
        },
        {
          id: "laser",
          weight: 3,
          tier: "legendary",
          pixels: [
            { x: 16, y: 10, role: "laser" },{ x: 17, y: 10, role: "laser" },{ x: 18, y: 10, role: "laser" },
            { x: 19, y: 10, role: "laser" },{ x: 20, y: 10, role: "laser" },{ x: 21, y: 10, role: "laser" },
          ],
        },
        {
          id: "3d_glasses",
          weight: 6,
          tier: "rare",
          pixels: [
            { x: 14, y: 10, role: "white" },{ x: 15, y: 10, role: "3d_left" },{ x: 16, y: 10, role: "3d_left" },
            { x: 17, y: 10, role: "white" },{ x: 18, y: 10, role: "3d_right" },{ x: 19, y: 10, role: "3d_right" },
            { x: 14, y: 11, role: "white" },{ x: 15, y: 11, role: "3d_left" },{ x: 16, y: 11, role: "3d_left" },
            { x: 17, y: 11, role: "white" },{ x: 18, y: 11, role: "3d_right" },{ x: 19, y: 11, role: "3d_right" },
          ],
        },
      ],
    },
    mouth: {
      type: "overlay",
      options: [
        {
          id: "cigarette",
          weight: 24,
          tier: "uncommon",
          pixels: [
            { x: 16, y: 14, role: "glasses_dark" },{ x: 17, y: 14, role: "glasses_dark" },{ x: 18, y: 14, role: "glasses_dark" },
            { x: 19, y: 14, role: "glasses_dark" },{ x: 20, y: 14, role: "cigarette_white" },{ x: 21, y: 14, role: "cigarette_white" },
            { x: 22, y: 14, role: "cigarette_white" },{ x: 23, y: 14, role: "cigarette_tip" },
          ],
        },
        {
          id: "neutral",
          weight: 24,
          tier: "common",
          pixels: [
            { x: 16, y: 14, role: "glasses_dark" },{ x: 17, y: 14, role: "glasses_dark" },{ x: 18, y: 14, role: "glasses_dark" },{ x: 19, y: 14, role: "glasses_dark" },
          ],
        },
        {
          id: "smirk",
          weight: 20,
          tier: "common",
          pixels: [
            { x: 16, y: 14, role: "glasses_dark" },{ x: 17, y: 14, role: "glasses_dark" },{ x: 18, y: 14, role: "glasses_dark" },{ x: 19, y: 15, role: "glasses_dark" },
          ],
        },
        {
          id: "teeth",
          weight: 14,
          tier: "uncommon",
          pixels: [
            { x: 16, y: 14, role: "teeth" },{ x: 17, y: 14, role: "teeth" },{ x: 18, y: 14, role: "teeth" },{ x: 19, y: 14, role: "teeth" },
          ],
        },
        {
          id: "pipe",
          weight: 8,
          tier: "rare",
          pixels: [
            { x: 16, y: 14, role: "glasses_dark" },{ x: 17, y: 14, role: "glasses_dark" },{ x: 18, y: 14, role: "glasses_dark" },
            { x: 19, y: 14, role: "glasses_dark" },{ x: 20, y: 14, role: "wood_pipe" },{ x: 21, y: 13, role: "wood_pipe" },{ x: 22, y: 13, role: "wood_pipe" },
          ],
          extraRoleBindings: {
            wood_pipe: 6,
          },
        },
        {
          id: "open",
          weight: 10,
          tier: "uncommon",
          pixels: [
            { x: 16, y: 14, role: "glasses_dark" },{ x: 17, y: 14, role: "glasses_dark" },{ x: 16, y: 15, role: "glasses_dark" },{ x: 17, y: 15, role: "glasses_dark" },
          ],
        },
      ],
    },
    hair: {
      type: "overlay",
      options: [
        {
          id: "mohawk_red",
          weight: 12,
          tier: "rare",
          pixels: [
            { x: 15, y: 5, role: "hair_red" },{ x: 16, y: 5, role: "hair_red" },
            { x: 15, y: 6, role: "hair_red" },{ x: 16, y: 6, role: "hair_red" },
            { x: 14, y: 7, role: "hair_red" },{ x: 15, y: 7, role: "hair_red" },{ x: 16, y: 7, role: "hair_red" },
            { x: 14, y: 8, role: "hair_red" },{ x: 15, y: 8, role: "hair_red" },{ x: 16, y: 8, role: "hair_red" },
            { x: 15, y: 9, role: "hair_red" },{ x: 16, y: 9, role: "hair_red" },
          ],
        },
        { id: "none", weight: 24, tier: "common", pixels: [] },
        {
          id: "beanie_black",
          weight: 18,
          tier: "uncommon",
          pixels: [
            { x: 12, y: 7, role: "hair_black" },{ x: 13, y: 7, role: "hair_black" },{ x: 14, y: 7, role: "hair_black" },{ x: 15, y: 7, role: "hair_black" },
            { x: 16, y: 7, role: "hair_black" },{ x: 17, y: 7, role: "hair_black" },{ x: 18, y: 7, role: "hair_black" },{ x: 19, y: 7, role: "hair_black" },
            { x: 11, y: 8, role: "hair_black" },{ x: 12, y: 8, role: "hair_black" },{ x: 13, y: 8, role: "hair_black" },{ x: 14, y: 8, role: "hair_black" },
            { x: 15, y: 8, role: "hair_black" },{ x: 16, y: 8, role: "hair_black" },{ x: 17, y: 8, role: "hair_black" },{ x: 18, y: 8, role: "hair_black" },
            { x: 19, y: 8, role: "hair_black" },{ x: 20, y: 8, role: "hair_black" },
          ],
        },
        {
          id: "hood_up_blue",
          weight: 18,
          tier: "uncommon",
          pixels: [
            { x: 11, y: 7, role: "hoodie_blue" },{ x: 12, y: 7, role: "hoodie_blue" },{ x: 13, y: 7, role: "hoodie_blue" },{ x: 14, y: 7, role: "hoodie_blue" },
            { x: 15, y: 7, role: "hoodie_blue" },{ x: 16, y: 7, role: "hoodie_blue" },{ x: 17, y: 7, role: "hoodie_blue" },{ x: 18, y: 7, role: "hoodie_blue" },
            { x: 19, y: 7, role: "hoodie_blue" },{ x: 20, y: 7, role: "hoodie_blue" },{ x: 11, y: 8, role: "hoodie_blue" },{ x: 20, y: 8, role: "hoodie_blue" },
            { x: 11, y: 9, role: "hoodie_blue" },{ x: 20, y: 9, role: "hoodie_blue" },{ x: 11, y: 10, role: "hoodie_blue" },{ x: 20, y: 10, role: "hoodie_blue" },
          ],
        },
        {
          id: "crown_gold",
          weight: 4,
          tier: "epic",
          pixels: [
            { x: 13, y: 7, role: "crown" },{ x: 14, y: 6, role: "crown" },{ x: 15, y: 7, role: "crown" },
            { x: 16, y: 6, role: "crown" },{ x: 17, y: 7, role: "crown" },{ x: 18, y: 6, role: "crown" },{ x: 19, y: 7, role: "crown" },
            { x: 14, y: 8, role: "crown" },{ x: 15, y: 8, role: "crown" },{ x: 16, y: 8, role: "crown" },{ x: 17, y: 8, role: "crown" },{ x: 18, y: 8, role: "crown" },
          ],
        },
        {
          id: "cap_blue",
          weight: 10,
          tier: "uncommon",
          pixels: [
            { x: 12, y: 7, role: "hoodie_blue" },{ x: 13, y: 7, role: "hoodie_blue" },{ x: 14, y: 7, role: "hoodie_blue" },{ x: 15, y: 7, role: "hoodie_blue" },
            { x: 16, y: 7, role: "hoodie_blue" },{ x: 17, y: 7, role: "hoodie_blue" },{ x: 18, y: 7, role: "hoodie_blue" },{ x: 19, y: 7, role: "hoodie_blue" },
            { x: 20, y: 8, role: "hoodie_blue" },{ x: 21, y: 8, role: "hoodie_blue" },
          ],
        },
      ],
    },
    clothing: {
      type: "overlay",
      options: [
        {
          id: "shirt_dark",
          weight: 32,
          tier: "common",
          pixels: [
            { x: 13, y: 21, role: "shirt_dark" },{ x: 14, y: 21, role: "shirt_dark" },{ x: 15, y: 21, role: "shirt_dark" },{ x: 16, y: 21, role: "shirt_dark" },{ x: 17, y: 21, role: "shirt_dark" },
            { x: 13, y: 22, role: "shirt_dark" },{ x: 14, y: 22, role: "shirt_dark" },{ x: 15, y: 22, role: "shirt_dark" },{ x: 16, y: 22, role: "shirt_dark" },{ x: 17, y: 22, role: "shirt_dark" },
            { x: 13, y: 23, role: "shirt_dark" },{ x: 14, y: 23, role: "shirt_dark" },{ x: 15, y: 23, role: "shirt_dark" },{ x: 16, y: 23, role: "shirt_dark" },{ x: 17, y: 23, role: "shirt_dark" },
          ],
        },
        {
          id: "hoodie_blue",
          weight: 30,
          tier: "common",
          pixels: [
            { x: 13, y: 21, role: "hoodie_blue" },{ x: 14, y: 21, role: "hoodie_blue" },{ x: 15, y: 21, role: "hoodie_blue" },{ x: 16, y: 21, role: "hoodie_blue" },{ x: 17, y: 21, role: "hoodie_blue" },
            { x: 13, y: 22, role: "hoodie_blue" },{ x: 14, y: 22, role: "hoodie_blue" },{ x: 15, y: 22, role: "hoodie_blue" },{ x: 16, y: 22, role: "hoodie_blue" },{ x: 17, y: 22, role: "hoodie_blue" },
            { x: 13, y: 23, role: "hoodie_blue" },{ x: 14, y: 23, role: "hoodie_blue" },{ x: 15, y: 23, role: "hoodie_blue" },{ x: 16, y: 23, role: "hoodie_blue" },{ x: 17, y: 23, role: "hoodie_blue" },
          ],
        },
        { id: "shirt_none", weight: 20, tier: "common", pixels: [] },
        {
          id: "hoodie_dark",
          weight: 14,
          tier: "uncommon",
          pixels: [
            { x: 13, y: 21, role: "hoodie_dark" },{ x: 14, y: 21, role: "hoodie_dark" },{ x: 15, y: 21, role: "hoodie_dark" },{ x: 16, y: 21, role: "hoodie_dark" },{ x: 17, y: 21, role: "hoodie_dark" },
            { x: 13, y: 22, role: "hoodie_dark" },{ x: 14, y: 22, role: "hoodie_dark" },{ x: 15, y: 22, role: "hoodie_dark" },{ x: 16, y: 22, role: "hoodie_dark" },{ x: 17, y: 22, role: "hoodie_dark" },
            { x: 13, y: 23, role: "hoodie_dark" },{ x: 14, y: 23, role: "hoodie_dark" },{ x: 15, y: 23, role: "hoodie_dark" },{ x: 16, y: 23, role: "hoodie_dark" },{ x: 17, y: 23, role: "hoodie_dark" },
          ],
        },
      ],
    },
    accessory: {
      type: "overlay",
      options: [
        { id: "none", weight: 54, tier: "common", pixels: [] },
        {
          id: "earring",
          weight: 14,
          tier: "uncommon",
          pixels: [{ x: 10, y: 14, role: "earring" }],
        },
        {
          id: "smoke",
          weight: 24,
          tier: "uncommon",
          pixels: [
            { x: 23, y: 13, role: "smoke" },{ x: 24, y: 12, role: "smoke" },{ x: 24, y: 11, role: "smoke" },{ x: 25, y: 11, role: "smoke" },{ x: 24, y: 10, role: "smoke" },
          ],
          requires: {
            mouth: ["cigarette", "pipe"],
          },
        },
        {
          id: "implant",
          weight: 8,
          tier: "rare",
          pixels: [
            { x: 12, y: 12, role: "visor" },
            { x: 12, y: 13, role: "glasses_dark" },
          ],
        },
      ],
    },
  },
  rules: [
    {
      id: "hood_up_needs_hoodie",
      type: "forceIf",
      if: { hair: ["hood_up_blue"] },
      then: { clothing: ["hoodie_blue", "hoodie_dark"] },
    },
    {
      id: "crown_no_hoodie",
      type: "forbidIf",
      if: { hair: ["crown_gold"] },
      not: { clothing: ["hoodie_blue", "hoodie_dark"] },
    },
    {
      id: "smoke_only_with_smokable_mouth",
      type: "forbidIf",
      if: { accessory: ["smoke"] },
      not: { mouth: ["neutral", "smirk", "teeth", "open"] },
    },
    {
      id: "female_less_beard",
      type: "weightModifier",
      when: { baseType: ["human_female"] },
      adjust: {
        beardShadow: {
          on: 8,
          off: 92,
        },
      },
    },
    {
      id: "alien_prefers_visor",
      type: "weightModifier",
      when: { baseType: ["alien"] },
      adjust: {
        eyes: {
          visor: 42,
          normal: 8,
          tired: 8,
          shades: 18,
          laser: 14,
          "3d_glasses": 10,
        },
      },
    },
    {
      id: "ape_no_mohawk",
      type: "forbidIf",
      if: { baseType: ["ape"] },
      not: { hair: ["mohawk_red"] },
    },
    {
      id: "zombie_prefers_cigarette_or_open",
      type: "weightModifier",
      when: { baseType: ["zombie"] },
      adjust: {
        mouth: {
          cigarette: 34,
          neutral: 12,
          smirk: 10,
          teeth: 10,
          pipe: 10,
          open: 24,
        },
      },
    },
  ],
  renderOrder: [
    "base_head_neck",
    "ear",
    "nose_bridge_and_tip",
    "clothing",
    "hair",
    "beardShadow",
    "eyes",
    "mouth",
    "accessory",
  ],
  random: {
    seedType: "uint64_or_timestamp",
    algorithm: "weighted_pick_with_rule_retries",
    maxRetries: 24,
  },
  presets: [
    {
      id: "ref_human_mohawk",
      label: "Human Mohawk",
      traits: {
        baseType: "human_male",
        skin: "light",
        beardShadow: "on",
        eyes: "shades",
        mouth: "cigarette",
        hair: "mohawk_red",
        clothing: "shirt_dark",
        accessory: "smoke",
      },
    },
    {
      id: "ref_street_degen",
      label: "Street Degen",
      traits: {
        baseType: "human_male",
        skin: "tan",
        beardShadow: "off",
        eyes: "tired",
        mouth: "smirk",
        hair: "beanie_black",
        clothing: "hoodie_blue",
        accessory: "earring",
      },
    },
    {
      id: "ref_alien_king",
      label: "Alien King",
      traits: {
        baseType: "alien",
        skin: "alien_green",
        beardShadow: "off",
        eyes: "visor",
        mouth: "cigarette",
        hair: "crown_gold",
        clothing: "shirt_none",
        accessory: "smoke",
      },
    },
  ],
  qualityGuards: {
    minTraitCountVisible: 4,
    forbidEmptyLook: true,
    emptyLookDefinition: {
      hair: ["none"],
      eyes: ["normal", "tired"],
      mouth: ["neutral"],
      accessory: ["none"],
      clothing: ["shirt_none"],
    },
    onEmptyLook: "reroll",
  },
});
