export const COLLECTION_SUPPLY = 100;
export const FEATURED_COLLECTION_IDS = [0,1,2,3];

export const GENERATED_COLLECTION = [
  {
    "id": 0,
    "name": "OnChainPixel #0",
    "base": "human dark",
    "background": "forest",
    "hair": "afro blue",
    "eyes": "shades",
    "mouth": "teeth",
    "shirt": "grey tee",
    "accessory": "scar",
    "tier": "Uncommon"
  },
  {
    "id": 1,
    "name": "OnChainPixel #1",
    "base": "human pale",
    "background": "slate",
    "hair": "beanie blonde",
    "eyes": "green",
    "mouth": "neutral",
    "shirt": "red hoodie",
    "accessory": "none",
    "tier": "Rare"
  },
  {
    "id": 2,
    "name": "OnChainPixel #2",
    "base": "human light",
    "background": "purple",
    "hair": "short purple",
    "eyes": "normal",
    "mouth": "neutral",
    "shirt": "green turtleneck",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 3,
    "name": "OnChainPixel #3",
    "base": "human pale",
    "background": "purple",
    "hair": "flat blue",
    "eyes": "cyan",
    "mouth": "smile",
    "shirt": "blue hoodie",
    "accessory": "earring gold",
    "tier": "Rare"
  },
  {
    "id": 4,
    "name": "OnChainPixel #4",
    "base": "human dark",
    "background": "ice",
    "hair": "short black",
    "eyes": "normal",
    "mouth": "neutral",
    "shirt": "none",
    "accessory": "none",
    "tier": "Uncommon"
  },
  {
    "id": 5,
    "name": "OnChainPixel #5",
    "base": "human tan",
    "background": "forest",
    "hair": "short green",
    "eyes": "blue",
    "mouth": "open",
    "shirt": "red tank",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 6,
    "name": "OnChainPixel #6",
    "base": "human pale",
    "background": "navy",
    "hair": "short black",
    "eyes": "normal",
    "mouth": "neutral",
    "shirt": "orange suit",
    "accessory": "none",
    "tier": "Rare"
  },
  {
    "id": 7,
    "name": "OnChainPixel #7",
    "base": "demon",
    "background": "forest",
    "hair": "short purple",
    "eyes": "normal",
    "mouth": "teeth",
    "shirt": "black turtleneck",
    "accessory": "nose ring",
    "tier": "Epic"
  },
  {
    "id": 8,
    "name": "OnChainPixel #8",
    "base": "human light",
    "background": "slate",
    "hair": "short blonde",
    "eyes": "yellow",
    "mouth": "smile",
    "shirt": "none",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 9,
    "name": "OnChainPixel #9",
    "base": "alien blue",
    "background": "forest",
    "hair": "short black",
    "eyes": "blue",
    "mouth": "frown",
    "shirt": "red tee",
    "accessory": "bandaid",
    "tier": "Epic"
  },
  {
    "id": 10,
    "name": "OnChainPixel #10",
    "base": "human dark",
    "background": "crimson",
    "hair": "mohawk blonde",
    "eyes": "laser",
    "mouth": "neutral",
    "shirt": "red hoodie",
    "accessory": "chain",
    "tier": "Uncommon"
  },
  {
    "id": 11,
    "name": "OnChainPixel #11",
    "base": "zombie",
    "background": "navy",
    "hair": "tall orange",
    "eyes": "normal",
    "mouth": "neutral",
    "shirt": "black tank",
    "accessory": "none",
    "tier": "Epic"
  },
  {
    "id": 12,
    "name": "OnChainPixel #12",
    "base": "human dark",
    "background": "gold",
    "hair": "tall black",
    "eyes": "blue",
    "mouth": "frown",
    "shirt": "blue vneck",
    "accessory": "earring gold",
    "tier": "Uncommon"
  },
  {
    "id": 13,
    "name": "OnChainPixel #13",
    "base": "zombie",
    "background": "midnight",
    "hair": "bald brown",
    "eyes": "closed",
    "mouth": "neutral",
    "shirt": "red collar",
    "accessory": "nose ring",
    "tier": "Epic"
  },
  {
    "id": 14,
    "name": "OnChainPixel #14",
    "base": "human pale",
    "background": "slate",
    "hair": "short red",
    "eyes": "red",
    "mouth": "open",
    "shirt": "white vneck",
    "accessory": "none",
    "tier": "Rare"
  },
  {
    "id": 15,
    "name": "OnChainPixel #15",
    "base": "human light",
    "background": "forest",
    "hair": "tall black",
    "eyes": "blue",
    "mouth": "neutral",
    "shirt": "yellow suit",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 16,
    "name": "OnChainPixel #16",
    "base": "human light",
    "background": "midnight",
    "hair": "ponytail blue",
    "eyes": "green",
    "mouth": "open",
    "shirt": "white tank",
    "accessory": "blush",
    "tier": "Common"
  },
  {
    "id": 17,
    "name": "OnChainPixel #17",
    "base": "human light",
    "background": "forest",
    "hair": "bald black",
    "eyes": "blue",
    "mouth": "small",
    "shirt": "black collar",
    "accessory": "scar",
    "tier": "Common"
  },
  {
    "id": 18,
    "name": "OnChainPixel #18",
    "base": "human light",
    "background": "navy",
    "hair": "mohawk brown",
    "eyes": "blue",
    "mouth": "smile",
    "shirt": "green tee",
    "accessory": "earring gold",
    "tier": "Common"
  },
  {
    "id": 19,
    "name": "OnChainPixel #19",
    "base": "human light",
    "background": "midnight",
    "hair": "tall pink",
    "eyes": "normal",
    "mouth": "smile",
    "shirt": "purple tee",
    "accessory": "blush",
    "tier": "Common"
  },
  {
    "id": 20,
    "name": "OnChainPixel #20",
    "base": "robot",
    "background": "ice",
    "hair": "short blue",
    "eyes": "normal",
    "mouth": "smile",
    "shirt": "white tee",
    "accessory": "mask",
    "tier": "Legendary"
  },
  {
    "id": 21,
    "name": "OnChainPixel #21",
    "base": "human tan",
    "background": "midnight",
    "hair": "spiky black",
    "eyes": "closed",
    "mouth": "frown",
    "shirt": "white collar",
    "accessory": "earring gold",
    "tier": "Common"
  },
  {
    "id": 22,
    "name": "OnChainPixel #22",
    "base": "human light",
    "background": "navy",
    "hair": "bald black",
    "eyes": "shades",
    "mouth": "open",
    "shirt": "black tee",
    "accessory": "monocle",
    "tier": "Common"
  },
  {
    "id": 23,
    "name": "OnChainPixel #23",
    "base": "human dark",
    "background": "midnight",
    "hair": "short black",
    "eyes": "cyan",
    "mouth": "grin",
    "shirt": "white suit",
    "accessory": "none",
    "tier": "Uncommon"
  },
  {
    "id": 24,
    "name": "OnChainPixel #24",
    "base": "human dark",
    "background": "crimson",
    "hair": "bald red",
    "eyes": "green",
    "mouth": "smile",
    "shirt": "white hoodie",
    "accessory": "earring gold",
    "tier": "Uncommon"
  },
  {
    "id": 25,
    "name": "OnChainPixel #25",
    "base": "human pale",
    "background": "ice",
    "hair": "spiky red",
    "eyes": "visor",
    "mouth": "teeth",
    "shirt": "red vneck",
    "accessory": "chain",
    "tier": "Rare"
  },
  {
    "id": 26,
    "name": "OnChainPixel #26",
    "base": "human light",
    "background": "slate",
    "hair": "bald blonde",
    "eyes": "normal",
    "mouth": "teeth",
    "shirt": "blue collar",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 27,
    "name": "OnChainPixel #27",
    "base": "human light",
    "background": "ice",
    "hair": "mohawk white",
    "eyes": "cyan",
    "mouth": "frown",
    "shirt": "black hoodie",
    "accessory": "earring silver",
    "tier": "Common"
  },
  {
    "id": 28,
    "name": "OnChainPixel #28",
    "base": "zombie",
    "background": "slate",
    "hair": "flat red",
    "eyes": "normal",
    "mouth": "open",
    "shirt": "none",
    "accessory": "blush",
    "tier": "Epic"
  },
  {
    "id": 29,
    "name": "OnChainPixel #29",
    "base": "human light",
    "background": "crimson",
    "hair": "spiky pink",
    "eyes": "normal",
    "mouth": "neutral",
    "shirt": "none",
    "accessory": "earring gold",
    "tier": "Common"
  },
  {
    "id": 30,
    "name": "OnChainPixel #30",
    "base": "human light",
    "background": "gold",
    "hair": "bald white",
    "eyes": "closed",
    "mouth": "open",
    "shirt": "green suit",
    "accessory": "nose ring",
    "tier": "Common"
  },
  {
    "id": 31,
    "name": "OnChainPixel #31",
    "base": "human pale",
    "background": "midnight",
    "hair": "bald blue",
    "eyes": "green",
    "mouth": "grin",
    "shirt": "pink vneck",
    "accessory": "monocle",
    "tier": "Rare"
  },
  {
    "id": 32,
    "name": "OnChainPixel #32",
    "base": "human dark",
    "background": "midnight",
    "hair": "beanie red",
    "eyes": "shades",
    "mouth": "neutral",
    "shirt": "none",
    "accessory": "nose ring",
    "tier": "Uncommon"
  },
  {
    "id": 33,
    "name": "OnChainPixel #33",
    "base": "human tan",
    "background": "midnight",
    "hair": "beanie brown",
    "eyes": "red",
    "mouth": "smile",
    "shirt": "none",
    "accessory": "chain",
    "tier": "Common"
  },
  {
    "id": 34,
    "name": "OnChainPixel #34",
    "base": "demon",
    "background": "ice",
    "hair": "flat orange",
    "eyes": "blue",
    "mouth": "neutral",
    "shirt": "white suit",
    "accessory": "none",
    "tier": "Epic"
  },
  {
    "id": 35,
    "name": "OnChainPixel #35",
    "base": "human tan",
    "background": "ice",
    "hair": "mohawk green",
    "eyes": "normal",
    "mouth": "small",
    "shirt": "green tee",
    "accessory": "earring silver",
    "tier": "Common"
  },
  {
    "id": 36,
    "name": "OnChainPixel #36",
    "base": "human dark",
    "background": "crimson",
    "hair": "afro black",
    "eyes": "cyan",
    "mouth": "neutral",
    "shirt": "green tee",
    "accessory": "none",
    "tier": "Uncommon"
  },
  {
    "id": 37,
    "name": "OnChainPixel #37",
    "base": "human tan",
    "background": "forest",
    "hair": "flat brown",
    "eyes": "cyan",
    "mouth": "open",
    "shirt": "yellow vneck",
    "accessory": "blush",
    "tier": "Common"
  },
  {
    "id": 38,
    "name": "OnChainPixel #38",
    "base": "alien blue",
    "background": "midnight",
    "hair": "short black",
    "eyes": "normal",
    "mouth": "fangs",
    "shirt": "yellow tee",
    "accessory": "none",
    "tier": "Epic"
  },
  {
    "id": 39,
    "name": "OnChainPixel #39",
    "base": "human dark",
    "background": "ice",
    "hair": "short brown",
    "eyes": "blue",
    "mouth": "teeth",
    "shirt": "purple hoodie",
    "accessory": "nose ring",
    "tier": "Uncommon"
  },
  {
    "id": 40,
    "name": "OnChainPixel #40",
    "base": "gold",
    "background": "midnight",
    "hair": "beanie black",
    "eyes": "visor",
    "mouth": "frown",
    "shirt": "white hoodie",
    "accessory": "blush",
    "tier": "Legendary"
  },
  {
    "id": 41,
    "name": "OnChainPixel #41",
    "base": "human light",
    "background": "navy",
    "hair": "side_part red",
    "eyes": "shades",
    "mouth": "teeth",
    "shirt": "purple tee",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 42,
    "name": "OnChainPixel #42",
    "base": "human light",
    "background": "gold",
    "hair": "afro brown",
    "eyes": "green",
    "mouth": "smile",
    "shirt": "grey hoodie",
    "accessory": "earring gold",
    "tier": "Common"
  },
  {
    "id": 43,
    "name": "OnChainPixel #43",
    "base": "human light",
    "background": "navy",
    "hair": "side_part black",
    "eyes": "shades",
    "mouth": "open",
    "shirt": "orange turtleneck",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 44,
    "name": "OnChainPixel #44",
    "base": "human tan",
    "background": "navy",
    "hair": "short blonde",
    "eyes": "normal",
    "mouth": "smile",
    "shirt": "black hoodie",
    "accessory": "blush",
    "tier": "Common"
  },
  {
    "id": 45,
    "name": "OnChainPixel #45",
    "base": "human light",
    "background": "ice",
    "hair": "flat blonde",
    "eyes": "cyan",
    "mouth": "smile",
    "shirt": "black hoodie",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 46,
    "name": "OnChainPixel #46",
    "base": "alien green",
    "background": "midnight",
    "hair": "flat pink",
    "eyes": "green",
    "mouth": "smile",
    "shirt": "green turtleneck",
    "accessory": "none",
    "tier": "Epic"
  },
  {
    "id": 47,
    "name": "OnChainPixel #47",
    "base": "human tan",
    "background": "forest",
    "hair": "long teal",
    "eyes": "green",
    "mouth": "grin",
    "shirt": "white tank",
    "accessory": "earring gold",
    "tier": "Common"
  },
  {
    "id": 48,
    "name": "OnChainPixel #48",
    "base": "human light",
    "background": "slate",
    "hair": "ponytail blue",
    "eyes": "shades",
    "mouth": "teeth",
    "shirt": "white collar",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 49,
    "name": "OnChainPixel #49",
    "base": "alien green",
    "background": "purple",
    "hair": "flat red",
    "eyes": "green",
    "mouth": "smile",
    "shirt": "white hoodie",
    "accessory": "none",
    "tier": "Epic"
  },
  {
    "id": 50,
    "name": "OnChainPixel #50",
    "base": "human light",
    "background": "crimson",
    "hair": "bald brown",
    "eyes": "blue",
    "mouth": "smile",
    "shirt": "pink tee",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 51,
    "name": "OnChainPixel #51",
    "base": "zombie",
    "background": "slate",
    "hair": "short blonde",
    "eyes": "normal",
    "mouth": "neutral",
    "shirt": "white turtleneck",
    "accessory": "blush",
    "tier": "Epic"
  },
  {
    "id": 52,
    "name": "OnChainPixel #52",
    "base": "human tan",
    "background": "crimson",
    "hair": "bald brown",
    "eyes": "closed",
    "mouth": "neutral",
    "shirt": "green hoodie",
    "accessory": "earring gold",
    "tier": "Common"
  },
  {
    "id": 53,
    "name": "OnChainPixel #53",
    "base": "human pale",
    "background": "slate",
    "hair": "bald red",
    "eyes": "blue",
    "mouth": "smile",
    "shirt": "yellow hoodie",
    "accessory": "none",
    "tier": "Rare"
  },
  {
    "id": 54,
    "name": "OnChainPixel #54",
    "base": "gold",
    "background": "purple",
    "hair": "long pink",
    "eyes": "normal",
    "mouth": "small",
    "shirt": "black vneck",
    "accessory": "none",
    "tier": "Legendary"
  },
  {
    "id": 55,
    "name": "OnChainPixel #55",
    "base": "human tan",
    "background": "slate",
    "hair": "short green",
    "eyes": "closed",
    "mouth": "frown",
    "shirt": "pink vneck",
    "accessory": "earring gold",
    "tier": "Common"
  },
  {
    "id": 56,
    "name": "OnChainPixel #56",
    "base": "demon",
    "background": "slate",
    "hair": "beanie red",
    "eyes": "cyan",
    "mouth": "teeth",
    "shirt": "red collar",
    "accessory": "blush",
    "tier": "Epic"
  },
  {
    "id": 57,
    "name": "OnChainPixel #57",
    "base": "human dark",
    "background": "crimson",
    "hair": "mohawk black",
    "eyes": "closed",
    "mouth": "small",
    "shirt": "black hoodie",
    "accessory": "none",
    "tier": "Uncommon"
  },
  {
    "id": 58,
    "name": "OnChainPixel #58",
    "base": "human light",
    "background": "navy",
    "hair": "flat silver",
    "eyes": "visor",
    "mouth": "small",
    "shirt": "blue tee",
    "accessory": "earring gold",
    "tier": "Common"
  },
  {
    "id": 59,
    "name": "OnChainPixel #59",
    "base": "human tan",
    "background": "slate",
    "hair": "short blue",
    "eyes": "normal",
    "mouth": "frown",
    "shirt": "black tee",
    "accessory": "monocle",
    "tier": "Common"
  },
  {
    "id": 60,
    "name": "OnChainPixel #60",
    "base": "zombie",
    "background": "purple",
    "hair": "beanie brown",
    "eyes": "normal",
    "mouth": "grin",
    "shirt": "black vneck",
    "accessory": "bandaid",
    "tier": "Epic"
  },
  {
    "id": 61,
    "name": "OnChainPixel #61",
    "base": "human tan",
    "background": "midnight",
    "hair": "tall white",
    "eyes": "green",
    "mouth": "neutral",
    "shirt": "blue hoodie",
    "accessory": "blush",
    "tier": "Common"
  },
  {
    "id": 62,
    "name": "OnChainPixel #62",
    "base": "human dark",
    "background": "forest",
    "hair": "afro black",
    "eyes": "green",
    "mouth": "small",
    "shirt": "yellow vneck",
    "accessory": "chain",
    "tier": "Uncommon"
  },
  {
    "id": 63,
    "name": "OnChainPixel #63",
    "base": "human light",
    "background": "navy",
    "hair": "afro brown",
    "eyes": "normal",
    "mouth": "smile",
    "shirt": "red tee",
    "accessory": "earring silver",
    "tier": "Common"
  },
  {
    "id": 64,
    "name": "OnChainPixel #64",
    "base": "alien green",
    "background": "navy",
    "hair": "short blonde",
    "eyes": "blue",
    "mouth": "neutral",
    "shirt": "none",
    "accessory": "tattoo",
    "tier": "Epic"
  },
  {
    "id": 65,
    "name": "OnChainPixel #65",
    "base": "human tan",
    "background": "midnight",
    "hair": "flat blue",
    "eyes": "green",
    "mouth": "neutral",
    "shirt": "orange tank",
    "accessory": "earring gold",
    "tier": "Common"
  },
  {
    "id": 66,
    "name": "OnChainPixel #66",
    "base": "human pale",
    "background": "crimson",
    "hair": "short black",
    "eyes": "closed",
    "mouth": "teeth",
    "shirt": "black vneck",
    "accessory": "tattoo",
    "tier": "Rare"
  },
  {
    "id": 67,
    "name": "OnChainPixel #67",
    "base": "human tan",
    "background": "forest",
    "hair": "afro brown",
    "eyes": "normal",
    "mouth": "open",
    "shirt": "none",
    "accessory": "earring gold",
    "tier": "Common"
  },
  {
    "id": 68,
    "name": "OnChainPixel #68",
    "base": "human tan",
    "background": "midnight",
    "hair": "short black",
    "eyes": "normal",
    "mouth": "open",
    "shirt": "black suit",
    "accessory": "earring silver",
    "tier": "Common"
  },
  {
    "id": 69,
    "name": "OnChainPixel #69",
    "base": "human tan",
    "background": "slate",
    "hair": "spiky black",
    "eyes": "normal",
    "mouth": "smile",
    "shirt": "orange tee",
    "accessory": "earring silver",
    "tier": "Common"
  },
  {
    "id": 70,
    "name": "OnChainPixel #70",
    "base": "alien blue",
    "background": "crimson",
    "hair": "long blue",
    "eyes": "visor",
    "mouth": "smile",
    "shirt": "orange suit",
    "accessory": "crown",
    "tier": "Epic"
  },
  {
    "id": 71,
    "name": "OnChainPixel #71",
    "base": "human dark",
    "background": "navy",
    "hair": "short purple",
    "eyes": "normal",
    "mouth": "smile",
    "shirt": "grey vneck",
    "accessory": "earring gold",
    "tier": "Uncommon"
  },
  {
    "id": 72,
    "name": "OnChainPixel #72",
    "base": "human light",
    "background": "navy",
    "hair": "afro black",
    "eyes": "normal",
    "mouth": "small",
    "shirt": "red collar",
    "accessory": "chain",
    "tier": "Common"
  },
  {
    "id": 73,
    "name": "OnChainPixel #73",
    "base": "human light",
    "background": "midnight",
    "hair": "spiky blonde",
    "eyes": "green",
    "mouth": "frown",
    "shirt": "white suit",
    "accessory": "bandaid",
    "tier": "Common"
  },
  {
    "id": 74,
    "name": "OnChainPixel #74",
    "base": "human tan",
    "background": "purple",
    "hair": "mohawk brown",
    "eyes": "closed",
    "mouth": "grin",
    "shirt": "yellow collar",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 75,
    "name": "OnChainPixel #75",
    "base": "human light",
    "background": "gold",
    "hair": "beanie blonde",
    "eyes": "normal",
    "mouth": "grin",
    "shirt": "purple collar",
    "accessory": "mask",
    "tier": "Common"
  },
  {
    "id": 76,
    "name": "OnChainPixel #76",
    "base": "human tan",
    "background": "purple",
    "hair": "short brown",
    "eyes": "yellow",
    "mouth": "small",
    "shirt": "none",
    "accessory": "chain",
    "tier": "Common"
  },
  {
    "id": 77,
    "name": "OnChainPixel #77",
    "base": "human light",
    "background": "purple",
    "hair": "flat green",
    "eyes": "red",
    "mouth": "neutral",
    "shirt": "blue tank",
    "accessory": "nose ring",
    "tier": "Common"
  },
  {
    "id": 78,
    "name": "OnChainPixel #78",
    "base": "human dark",
    "background": "forest",
    "hair": "spiky orange",
    "eyes": "green",
    "mouth": "neutral",
    "shirt": "blue tee",
    "accessory": "earring gold",
    "tier": "Uncommon"
  },
  {
    "id": 79,
    "name": "OnChainPixel #79",
    "base": "alien blue",
    "background": "ice",
    "hair": "spiky black",
    "eyes": "yellow",
    "mouth": "open",
    "shirt": "white collar",
    "accessory": "bandaid",
    "tier": "Epic"
  },
  {
    "id": 80,
    "name": "OnChainPixel #80",
    "base": "human dark",
    "background": "slate",
    "hair": "beanie brown",
    "eyes": "normal",
    "mouth": "small",
    "shirt": "blue vneck",
    "accessory": "earring silver",
    "tier": "Uncommon"
  },
  {
    "id": 81,
    "name": "OnChainPixel #81",
    "base": "human dark",
    "background": "crimson",
    "hair": "long red",
    "eyes": "closed",
    "mouth": "frown",
    "shirt": "green turtleneck",
    "accessory": "scar",
    "tier": "Uncommon"
  },
  {
    "id": 82,
    "name": "OnChainPixel #82",
    "base": "human light",
    "background": "forest",
    "hair": "tall black",
    "eyes": "laser",
    "mouth": "small",
    "shirt": "red vneck",
    "accessory": "mask",
    "tier": "Common"
  },
  {
    "id": 83,
    "name": "OnChainPixel #83",
    "base": "human dark",
    "background": "navy",
    "hair": "tall black",
    "eyes": "green",
    "mouth": "small",
    "shirt": "black tee",
    "accessory": "earring gold",
    "tier": "Uncommon"
  },
  {
    "id": 84,
    "name": "OnChainPixel #84",
    "base": "human dark",
    "background": "crimson",
    "hair": "flat brown",
    "eyes": "normal",
    "mouth": "small",
    "shirt": "pink tank",
    "accessory": "mask",
    "tier": "Uncommon"
  },
  {
    "id": 85,
    "name": "OnChainPixel #85",
    "base": "human tan",
    "background": "midnight",
    "hair": "flat brown",
    "eyes": "green",
    "mouth": "small",
    "shirt": "white tee",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 86,
    "name": "OnChainPixel #86",
    "base": "human light",
    "background": "slate",
    "hair": "afro brown",
    "eyes": "normal",
    "mouth": "neutral",
    "shirt": "none",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 87,
    "name": "OnChainPixel #87",
    "base": "human light",
    "background": "forest",
    "hair": "tall black",
    "eyes": "visor",
    "mouth": "frown",
    "shirt": "blue collar",
    "accessory": "monocle",
    "tier": "Common"
  },
  {
    "id": 88,
    "name": "OnChainPixel #88",
    "base": "human tan",
    "background": "navy",
    "hair": "ponytail red",
    "eyes": "normal",
    "mouth": "grin",
    "shirt": "green hoodie",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 89,
    "name": "OnChainPixel #89",
    "base": "human tan",
    "background": "midnight",
    "hair": "tall black",
    "eyes": "cyan",
    "mouth": "frown",
    "shirt": "red tank",
    "accessory": "bandaid",
    "tier": "Common"
  },
  {
    "id": 90,
    "name": "OnChainPixel #90",
    "base": "human tan",
    "background": "crimson",
    "hair": "short red",
    "eyes": "blue",
    "mouth": "teeth",
    "shirt": "white turtleneck",
    "accessory": "chain",
    "tier": "Common"
  },
  {
    "id": 91,
    "name": "OnChainPixel #91",
    "base": "human light",
    "background": "purple",
    "hair": "flat blue",
    "eyes": "cyan",
    "mouth": "neutral",
    "shirt": "blue turtleneck",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 92,
    "name": "OnChainPixel #92",
    "base": "human pale",
    "background": "slate",
    "hair": "short green",
    "eyes": "green",
    "mouth": "neutral",
    "shirt": "red tank",
    "accessory": "blush",
    "tier": "Rare"
  },
  {
    "id": 93,
    "name": "OnChainPixel #93",
    "base": "zombie",
    "background": "crimson",
    "hair": "long black",
    "eyes": "normal",
    "mouth": "smile",
    "shirt": "white hoodie",
    "accessory": "none",
    "tier": "Epic"
  },
  {
    "id": 94,
    "name": "OnChainPixel #94",
    "base": "human light",
    "background": "navy",
    "hair": "beanie blonde",
    "eyes": "blue",
    "mouth": "teeth",
    "shirt": "green turtleneck",
    "accessory": "earring gold",
    "tier": "Common"
  },
  {
    "id": 95,
    "name": "OnChainPixel #95",
    "base": "human light",
    "background": "midnight",
    "hair": "mohawk brown",
    "eyes": "blue",
    "mouth": "neutral",
    "shirt": "blue vneck",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 96,
    "name": "OnChainPixel #96",
    "base": "robot",
    "background": "midnight",
    "hair": "tall blonde",
    "eyes": "normal",
    "mouth": "smile",
    "shirt": "black hoodie",
    "accessory": "none",
    "tier": "Legendary"
  },
  {
    "id": 97,
    "name": "OnChainPixel #97",
    "base": "human tan",
    "background": "ice",
    "hair": "short red",
    "eyes": "normal",
    "mouth": "grin",
    "shirt": "red suit",
    "accessory": "earring silver",
    "tier": "Common"
  },
  {
    "id": 98,
    "name": "OnChainPixel #98",
    "base": "human tan",
    "background": "slate",
    "hair": "mohawk red",
    "eyes": "normal",
    "mouth": "neutral",
    "shirt": "green hoodie",
    "accessory": "none",
    "tier": "Common"
  },
  {
    "id": 99,
    "name": "OnChainPixel #99",
    "base": "human dark",
    "background": "ice",
    "hair": "beanie blue",
    "eyes": "normal",
    "mouth": "neutral",
    "shirt": "none",
    "accessory": "earring gold",
    "tier": "Uncommon"
  }
];
